### ISSUE TITLE
Livestream not starting automatically

### ISSUE THREAD

**Issue by perotom** [ddimensia/yi_4k_hacks#3]
I love these hacks! Sadly only the QR code scanner for live streaming starts but it doesn't connect automatically to the wifi. Any ideas?

**Comment by ddimensia** [comment]
Which version of the firmware do you have.  I know that newer firmwares don't work the same, I may have a fix but I haven't taken the time to write a single set of scripts that work across multiple firmware versions.

**Comment by perotom** [comment]
I am using firmware version `1.10.9 Build 2748r`. It is stuck in the qr code scanning screen. Does it mean I can rule out wifi configuration problems or not?

**Comment by ddimensia** [comment]
Hmm, that's the same firmware version I'm running.  I had one camera running a much older version that required modifications but it works fine since updating it.   My first thought is perhaps you didn't create the `autortmp_enable.script` file in the root of the SD card, or whatever OS you're using to create it is hiding something like a `.txt` extension.  The basic way it works is that a script does some setup, creating a file that the qr scanner looks for and then it starts the qr scanning process.  If that first part doesn't happen then the qr scanner doesn't exit.

**Comment by perotom** [comment]
This really was the problem. Thank you very much. Great work!
